config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:index]
  resources :events
  get '/search', to: 'events#search', as: 'search_events'
  get '/search_by_category', to: 'events#search_by_category', as: 'search_by_category_events'
  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  root "users#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :events

  validates :name, presence: true, uniqueness: true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  belongs_to :category

  validates :name, presence: true
  validates :date, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :events

  #validates :email, presence: true
  #validates :password, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :surname])
  end
end

app/controllers/events_controller.rb
require 'geocoder'

class EventsController < ApplicationController
  skip_before_action :verify_authenticity_token

  def index
  end

  def new
    @event = Event.new
  end

  def show
    @event = Event.find(params[:id])
    @weather = get_weather
  end

  def create
    @event = Event.new(event_params)

    if @event.save
      flash[:success] = 'Event was successfully created.'
      redirect_to events_path
    else
      flash[:error] = 'Please fill all fields correctly.'
      render :new
    end
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])

    if @event.update(event_params)
      flash[:success] = 'Item was updated'
      redirect_to users_path
    else
      flash[:error] = 'Please fill all fields correctly'
      redirect_to users_path
    end
  end

  def destroy
    @event = Event.find(params[:id])
    if @event.destroy
      flash[:success] = 'Item was successfully destroyed'
      redirect_to users_path
    else
      flash[:error] = 'Failed to destroy item'
      redirect_to users_path
    end
  end

  def search
    @user = current_user
    @events = if params[:search_term]
                @user.events.where("name LIKE ?", "%#{params[:search_term]}%")
              else
                @user.events
              end
  end

  def search_by_category
    @user = current_user
    if params[:search_term]
      @events = @user.events.joins(:category).where("categories.name LIKE ?", "%#{params[:search_term]}%")
    else
      @events = @user.events
    end
  end

  private

  def event_params
    params.require(:event).permit(:name, :date, :description, :user_id, :category_id)
  end

  def get_weather
    api_key = 'fc5c5b79bb4822c5f03b82a3a926b1fe'
    response = HTTParty.get("https://api.openweathermap.org/data/2.5/weather?q=minsk&appid=#{api_key}")
    if response.code == 200
      weather_data = JSON.parse(response.body)
      return weather_data
    end
  end

end

app/controllers/users_controller.rb
require 'kaminari'

class UsersController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_action :authenticate_user!

  def index
    @user = current_user
    @events = Event.where(user_id: current_user.id)

    if params[:search].present?
      @events = @events.where('name ILIKE ?', "%#{params[:search]}%")
    end

    if params[:category_id].present?
      @events = @events.joins(:category).where(categories: { name: params[:category_id] })
    end

    @paginated_events = @events.page(params[:page]).per(5) # Используем пагинацию Kaminari

    @upcoming_events_count = @events.where("date > ?", Date.today).count
    @today_events_count = @events.where(date: Date.today).count

    @categories = Category.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/edit.html.erb
<h2 style="color: #B00100; margin: 0 auto">Edit item <%= @event.name %> </h2>
<br/>

<%= form_for @event, url: event_path(@event), method: :put do |form| %>
  <%= form.label :name %>
  <%= form.text_field :name %>

  <%= form.label :date %>
  <%= form.date_field :date %>

  <%= form.label :description %>
  <%= form.text_field :description %>

  <%= form.submit "Update", class: "btn btn-large btn-primary" %>
<% end %>

app/views/events/new.html.erb
<h2>Create new event</h2>

<%= form_for @event do |form| %>
  <%= form.label :name %>
  <%= form.text_field :name %>

  <%= form.label :date %>
  <%= form.date_field :date %>

  <%= form.label :description %>
  <%= form.text_area :description %>

  <%= form.label :user_id %>
  <%= form.text_field :user_id %>

  <%= form.label :category_id %>
  <%= form.text_field :category_id %>

  <%= form.submit "Save" %>
<% end %>

app/views/events/search.html.erb
<h2>Search events</h2>

<%= form_tag search_events_path, method: :get do %>
  <%= label_tag :search_term %>
  <%= text_field_tag :search_term, params[:search_term] %>
  <%= submit_tag "Search", class: "btn btn-large btn-primary" %>
<% end %>

<table>
  <thead>
  <tr>
    <th>ID</th>
    <th>Name</th>
    <th>Date</th>
    <th>Category</th>
  </tr>
  </thead>
  <tbody>
  <% @events.each do |event| %>
    <tr>
      <td><%= event.id %></td>
      <td><%= link_to event.name, event_path(event) %></td>
      <td><%= event.date %></td>
      <td><%= event.category %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/events/search_by_category.html.erb
<h2 style="color: #B00100; margin: 0 auto">Search events by category</h2>
<br/>
<%= form_tag search_by_category_events_path, method: :get do %>
  <%= label_tag :search_term, "Search by Category Name" %>
  <%= text_field_tag :search_term, params[:search_term] %>
  <%= submit_tag "Search", class: "btn btn-large btn-primary" %>
<% end %>

<br/>

<table>
  <thead>
  <tr>
    <th>ID</th>
    <th>Название</th>
    <th>Дата</th>
    <th>Категория</th>
  </tr>
  </thead>
  <tbody>
  <% @events.each do |event| %>
    <tr>
      <td><%= event.id %></td>
      <td><%= link_to event.name, event_path(event) %></td>
      <td><%= event.date %></td>
      <td><%= event.category %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/events/show.html.erb
<h2 style="color: #B00100; margin: 0 auto">Show event</h2>

<ul>
  <li>Name: <%= @event.name %> </li>
  <li>Date: <%= @event.date %> </li>
  <li>Description: <%= @event.description %></li>
</ul>

<br/>

<% if @weather %>
  <h3>Погодные условия</h3>
  <ul>
    <li>Температура: <%= (@weather.dig('main', 'temp') - 273.15).round(2) %>°C</li>
  </ul>
<% else %>
  <p>Погода недоступна.</p>
<% end %>

<%= link_to 'Edit', edit_event_path(@event) %>
<%= button_to "Delete #{@event.name}", event_path(@event), method: :delete %>

app/views/include/main/_notification.html.erb
<% if notice %>
  <p class="notice alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="notice alert-danger"><%= alert %></p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyFuckingProject</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag 'https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css'%>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
  <style>
      .user-actions {
          position: fixed;
          top: 0;
          right: 0;
          margin: 10px;
      }
  </style>
</head>

<body>
<header>
  <%= render 'include/auth/auth_header' %>
  <% if user_signed_in? %>
    <div class="user-actions">
      <a href="#" class="btn btn-dark btn-sm">
        Добро пожаловать, <%= current_user.email %>
      </a>
      <%= link_to 'Выход', destroy_user_session_path,
                  method: :delete,
                  class: "btn btn-dark btn-sm ms-2" %>
      <%= link_to 'Редактирование', edit_user_registration_path,
                  class: "btn btn-dark btn-sm ms-2" %>
    </div>
  <% else %>
    <div class="user-actions">
      <%= link_to 'Вход', new_user_session_path,
                  class: "btn btn-dark btn-sm" %>
      <%= link_to 'Регистрация', new_user_registration_path,
                  class: "btn btn-dark btn-sm ms-2" %>
    </div>
  <% end %>
</header>

<div>
  <%= render 'include/main/notification' %>
  <%= yield %>
</div>
</body>
</html>

app/views/users/index.html.erb
<!-- app/views/events/index.html.erb -->
<!DOCTYPE html>
<html>
<head>
  <title>Выбор секций</title>
  <style>
      .section {
          display: none;
      }

      .active {
          display: block;
      }
  </style>
  <script>
      function showSection(sectionName) {
          var sections = document.getElementsByClassName("section");
          for (var i = 0; i < sections.length; i++) {
              sections[i].style.display = "none";
          }

          var selectedSection = document.getElementById(sectionName);
          selectedSection.style.display = "block";
      }
  </script>
</head>
<body>
<div style="text-align: center; margin-top: 200px">
  <button onclick="showSection('me')">Me</button>
  <button onclick="showSection('events')">Events</button>
  <button onclick="showSection('categories')">Categories</button>
</div>

<div id="me" class="section active" style="text-align: center; margin-top: 20px">
  <h2>Привет, <%= @user.name %></h2>
  <h2>Предстоящие события</h2>
  <p>Количество предстоящих событий: <%= @upcoming_events_count %></p>
  <p>Количество событий на сегодня: <%= @today_events_count %></p>
</div>

<div id="events" class="section" style="text-align: center; margin-top: 20px">
  <h2>События пользователя</h2>
  <h1>Search Events</h1>

  <%= form_tag(users_path, method: :get, id: "search-form") do %>
    <div>
      <%= label_tag :search, 'Event Name' %>
      <%= text_field_tag :search, params[:search] %>
    </div>

    <div>
      <%= label_tag :category_id, 'Category' %>
      <%= select_tag :category_id, options_from_collection_for_select(@categories, :name, :name, params[:category_id]), include_blank: true %>
    </div>

    <%= submit_tag 'Search' %>
  <% end %>

  <h2>Results</h2>

  <table>
    <thead>
    <tr>
      <th>Name</th>
      <th>Date</th>
      <th>Description</th>
      <th>Category</th>
    </tr>
    </thead>
    <tbody>
    <% @paginated_events.each do |event| %>
      <tr>
        <td><%= event.name %></td>
        <td><%= event.date %></td>
        <td><%= event.description %></td>
        <td><%= event.category.name if event.category %></td>
      </tr>
    <% end %>
    </tbody>
  </table>

  <%= paginate @paginated_events %>

  <div style="text-align: center; margin-top: 20px">
    <%= link_to 'Create new event', new_event_path %>
    <%= link_to 'Search', search_events_path %>
    <%= link_to 'Search by category', search_by_category_events_path %>
  </div>
</div>

<div id="categories" class="section" style="text-align: center; margin-top: 20px">
  <h2>Секция Categories</h2>
</div>
</body>
</html>